### ISSUE TITLE
where is chapter_num set?

### ISSUE THREAD

**Issue by miyagawa** [neilberkman/chapter-demo#1]
I was able to port the chapter tagging script from Python to Ruby using this repo as an example, Thank you!

I noticed that there's `:chapter_num` need to be set for each chapter and the demo script doesn't seem to set it, unless I'm missing something. I updated my code to use the array index as its number, but for a future reader of this demo, I suggest to set the correct chapter number in the script.

**Comment by iamazeem** [comment]
@miyagawa 
I just noticed that too that it's **not** an incrementing number.
Actually, the correct term would be `element_id`, not `chapter_num`.
So, in its current state, the script sets the same `element_id` for chapters.
I agree that it should be set properly for future references.

@neilberkman 
Can you please verify this on your machine and update it accordingly?

**Comment by neilberkman** [comment]
@miyagawa glad you found it useful and thanks for the bug report (and thanks for following up @iamAzeem)! Fixed in 42218f58cabba7b373e401ea1f3a97676af3fac7
